<?php

namespace rocinante\domain\model;

require_once 'rocinante/domain/model/Domain.php';

/**
 * Message is a domain class that represents a message sent or received by a user.
 */
class Message extends Domain
{

   /**
    * Creates a new message.
    * @param int $mailid A univocal identifier for the message or null whether it is a new one.
    */
   public function __construct($mailid = null)
   {
      $fields = array('MailId' => 'i',
                      'Time' => 's',
                      'Subject' => 's',
                      'Body' => 's');
      parent::__construct($fields);
      if ($mailid !== null)
      {
         parent::set('MailId', $mailid);
      }
   }

   /**
    * Sets a univocal ID for this object generated by the database because the ID field has the AUTO
    * INCREMENT attribute.
    */
   public function setLastInsertId($value)
   {
      if ($this->get('MailId') === null)
      {
         $this->set('MailId', $value);
      }
   }

}
