<?php

namespace rocinante\domain\model;

require_once 'rocinante/domain/model/Domain.php';

/**
 * Task is a domain class that represents the table that stores translation, revision, and updating
 * tasks that are in progress.
 */
class Task extends Domain
{

   /**
    * Creates a new translation status.
    * @param int $taskid A univocal identifier for the task or null whether it is a new task.
    */
   public function __construct($taskid = null)
   {
      $fields = array('TaskId' => 'i',
                      'TableId' => 'i',
                      'UserId' => 'i',
                      'AssignerId' => 'i',
                      'Date' => 's',
                      'Type' => 's',
                      'Term' => 's',
                      'Size' => 'i',
                      'Progress' => 'd');
      parent::__construct($fields);
      if ($taskid !== null)
      {
         parent::set('TaskId', $taskid);
      }
   }

   /**
    * Sets a univocal ID that is generated by the database for this task.
    */
   public function setLastInsertId($value)
   {
      $this->set('TaskId', $value);
   }

}
