<?php

namespace rocinante\domain\model;

require_once 'rocinante/domain/model/Domain.php';

/**
 * TermType is a domain class that represents term categories. They are used to classify game terms
 * that belong to the glossary.
 */
class TermType extends Domain
{

   /**
    * Creates a new type of term.
    * @param int $typeid A univocal identifier for the term type or null whether it is a new type.
    */
   public function __construct($typeid = null)
   {
      $fields = array('TypeId' => 's',
                      'Description' => 's');
      parent::__construct($fields);
      if ($typeid !== null)
      {
         parent::set('TypeId', $typeid);
      }
   }

   /**
    * Sets a univocal ID for this object generated by the database.
    * @param int $value A number.
    */
   public function setLastInsertId($value)
   {
      if ($this->get('TypeId') === null)
      {
         $this->set('TypeId', $value);
      }
   }

}
