<?php

namespace rocinante\domain\model;

require_once 'rocinante/domain/model/Domain.php';

/**
 * User is a domain class that represents a translator, an advisor, or an admin.
 */
class User extends Domain
{

   /**
    * Creates a new user.
    * @param int $userid A univocal identifier for the user or null whether it is a new user.
    */
   public function __construct($userid = null)
   {
      $fields = array('UserId' => 'i',
                      'Username' => 's',
                      'FirstName' => 's',
                      'Gender' => 's',
                      'Email' => 's',
                      'Password' => 's',
                      'SessionId' => 's',
                      'Type' => 's',
                      'Theme' => 's',
                      'Since' => 's',
                      'IsActive' => 'i');
      parent::__construct($fields);
      if ($userid !== null)
      {
         parent::set('UserId', $userid);
      }
   }

   /**
    * Sets a univocal ID for this object generated by the database.
    * @param int $value A number.
    */
   public function setLastInsertId($value)
   {
      if ($this->get('UserId') === null)
      {
         $this->set('UserId', $value);
      }
   }

}
